import React from 'react';

const InvoicePrint = ({ order, items, customer }: any) => {
  return (
    <div className="print-only p-10 text-black bg-white min-h-screen font-sans">
      {/* Shop Header */}
      <div className="flex justify-between border-b-4 border-black pb-6">
        <div>
          <h1 className="text-4xl font-black tracking-tighter uppercase leading-none">SmartBiz ERP</h1>
          <p className="text-sm font-bold mt-2">123, Highlevel Road, Maharagama.</p>
          <p className="text-sm">Tel: 011 234 5678 | 077 123 4567</p>
        </div>
        <div className="text-right">
          <h2 className="text-4xl font-black text-gray-300">INVOICE</h2>
          <p className="text-sm font-bold mt-2">NO: <span className="font-mono">{order?.order_no}</span></p>
          <p className="text-sm">DATE: {order?.order_date}</p>
        </div>
      </div>

      {/* Customer Info */}
      <div className="my-8 grid grid-cols-2">
        <div>
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Bill To:</p>
          <p className="text-xl font-black uppercase">{customer?.name || 'Cash Customer'}</p>
          <p className="text-sm">{customer?.address || 'N/A'}</p>
          <p className="text-sm font-bold">{customer?.phone || ''}</p>
        </div>
      </div>

      {/* Items Table */}
      <table className="w-full text-sm mb-10 border-collapse">
        <thead>
          <tr className="border-b-2 border-black text-left uppercase text-[11px] font-black">
            <th className="py-3 px-1">Description</th>
            <th className="py-3 px-1 text-center w-20">Qty</th>
            <th className="py-3 px-1 text-right w-32">Unit Price</th>
            <th className="py-3 px-1 text-right w-32">Total (LKR)</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-300">
          {items.map((item: any, index: number) => (
            <tr key={index} className="border-b border-gray-100">
              <td className="py-4 px-1">
                <p className="font-bold uppercase">{item.product_name || 'Product'}</p>
                {item.is_free && <span className="text-[9px] bg-black text-white px-1 font-bold">FREE ISSUE</span>}
              </td>
              <td className="py-4 px-1 text-center font-bold">{item.quantity}</td>
              <td className="py-4 px-1 text-right font-mono">{item.unit_price?.toLocaleString('en-LK', {minimumFractionDigits: 2})}</td>
              <td className="py-4 px-1 text-right font-black font-mono">{item.total_price?.toLocaleString('en-LK', {minimumFractionDigits: 2})}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Summary Area */}
      <div className="flex justify-end mt-12">
        <div className="w-72 space-y-3">
          <div className="flex justify-between text-sm border-b pb-1">
            <span className="font-bold uppercase text-gray-500">Sub Total</span>
            <span className="font-bold">{(order?.total_amount || 0).toLocaleString('en-LK', {minimumFractionDigits: 2})}</span>
          </div>
          <div className="flex justify-between text-sm border-b pb-1 text-red-600">
            <span className="font-bold uppercase">Discount</span>
            <span className="font-bold">- {(order?.discount_amount || 0).toLocaleString('en-LK', {minimumFractionDigits: 2})}</span>
          </div>
          <div className="flex justify-between bg-black text-white p-3 rounded-lg shadow-lg">
            <span className="text-sm font-black uppercase tracking-widest">Grand Total</span>
            <span className="text-xl font-black font-mono">LKR {(order?.net_amount || 0).toLocaleString('en-LK', {minimumFractionDigits: 2})}</span>
          </div>
        </div>
      </div>

      {/* Signatures & Footer */}
      <div className="mt-24">
        <div className="flex justify-between items-end px-4">
          <div className="text-center w-48 border-t-2 border-black pt-2">
            <p className="text-[10px] font-black uppercase">Authorized Signature</p>
          </div>
          <div className="text-center w-48 border-t-2 border-black pt-2">
            <p className="text-[10px] font-black uppercase">Customer Signature</p>
          </div>
        </div>
        <div className="mt-16 text-center border-t border-gray-200 pt-6">
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Generated by SmartBiz ERP System</p>
        </div>
      </div>
    </div>
  );
};

export default InvoicePrint;